name: Run Instrumentation Tests

on:
    workflow_dispatch:
    push:
      branches:
        - develop

jobs:
  instrumentation-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains' 
          java-version: '17' 

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Android app
        run: ./gradlew assembleDebug assembleAndroidTest

      - name: Create and start emulator
        uses: android-actions/setup-android@v3
        with:
          emulator: 'system-images;android-30;google_apis;x86_64' # Definisce l'immagine di sistema
          avd-name: test
          api-level: 30
          force: true

      - name: Run connectedCheck
        run: ./gradlew connectedCheck